# Generated by Django 5.2 on 2025-04-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salesreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='packaging_price_multipier',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='packaging_type',
        ),
        migrations.DeleteModel(
            name='SalesReports',
        ),
    ]
