# Generated by Django 5.2 on 2025-04-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_medicines_packaging_price_multipier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='created_by',
            new_name='staff',
        ),
    ]
